// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.9.0
// source: proto/borrowLogs.proto

//
//ID int64 `gorm:"primary_key;auto_increment;not_null" json:"id"`
//ReqWID int64 `json:"req_wid"`//转借者ID
//RspWID int64 `json:"rsp_wid"`//收到者ID
//Confirm bool `json:"confirm"`//对方是否已确认
//Reason string `json:"reason"`//原因说明
//Boss int8 `json:"boss"`//是否需要boss确认，1代表不需要，2代表需要且未确认，3代表需要且确认

package borrowLogs

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ReqToOther struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqWID int64  `protobuf:"varint,1,opt,name=ReqWID,proto3" json:"ReqWID,omitempty"`
	RspWID int64  `protobuf:"varint,2,opt,name=RspWID,proto3" json:"RspWID,omitempty"`
	PID    int64  `protobuf:"varint,3,opt,name=PID,proto3" json:"PID,omitempty"` //产品ID
	Reason string `protobuf:"bytes,4,opt,name=Reason,proto3" json:"Reason,omitempty"`
}

func (x *ReqToOther) Reset() {
	*x = ReqToOther{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_borrowLogs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqToOther) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqToOther) ProtoMessage() {}

func (x *ReqToOther) ProtoReflect() protoreflect.Message {
	mi := &file_proto_borrowLogs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqToOther.ProtoReflect.Descriptor instead.
func (*ReqToOther) Descriptor() ([]byte, []int) {
	return file_proto_borrowLogs_proto_rawDescGZIP(), []int{0}
}

func (x *ReqToOther) GetReqWID() int64 {
	if x != nil {
		return x.ReqWID
	}
	return 0
}

func (x *ReqToOther) GetRspWID() int64 {
	if x != nil {
		return x.RspWID
	}
	return 0
}

func (x *ReqToOther) GetPID() int64 {
	if x != nil {
		return x.PID
	}
	return 0
}

func (x *ReqToOther) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Req_Boss_Confirm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"` //根据ID确认同意
}

func (x *Req_Boss_Confirm) Reset() {
	*x = Req_Boss_Confirm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_borrowLogs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_Boss_Confirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_Boss_Confirm) ProtoMessage() {}

func (x *Req_Boss_Confirm) ProtoReflect() protoreflect.Message {
	mi := &file_proto_borrowLogs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_Boss_Confirm.ProtoReflect.Descriptor instead.
func (*Req_Boss_Confirm) Descriptor() ([]byte, []int) {
	return file_proto_borrowLogs_proto_rawDescGZIP(), []int{1}
}

func (x *Req_Boss_Confirm) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type Rsp_All struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` //是否成功
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Rsp_All) Reset() {
	*x = Rsp_All{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_borrowLogs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp_All) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp_All) ProtoMessage() {}

func (x *Rsp_All) ProtoReflect() protoreflect.Message {
	mi := &file_proto_borrowLogs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp_All.ProtoReflect.Descriptor instead.
func (*Rsp_All) Descriptor() ([]byte, []int) {
	return file_proto_borrowLogs_proto_rawDescGZIP(), []int{2}
}

func (x *Rsp_All) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Rsp_All) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_borrowLogs_proto protoreflect.FileDescriptor

var file_proto_borrowLogs_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x4c, 0x6f,
	0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77,
	0x4c, 0x6f, 0x67, 0x73, 0x22, 0x68, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x5f, 0x74, 0x6f, 0x5f, 0x6f,
	0x74, 0x68, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x71, 0x57, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x65, 0x71, 0x57, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x52, 0x73, 0x70, 0x57, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x73,
	0x70, 0x57, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x50, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x22,
	0x0a, 0x10, 0x52, 0x65, 0x71, 0x5f, 0x42, 0x6f, 0x73, 0x73, 0x5f, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x49, 0x44, 0x22, 0x3b, 0x0a, 0x07, 0x52, 0x73, 0x70, 0x5f, 0x41, 0x6c, 0x6c, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32,
	0x8a, 0x01, 0x0a, 0x0a, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x39,
	0x0a, 0x08, 0x74, 0x6f, 0x5f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x62, 0x6f, 0x72,
	0x72, 0x6f, 0x77, 0x4c, 0x6f, 0x67, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x5f, 0x74, 0x6f, 0x5f, 0x6f,
	0x74, 0x68, 0x65, 0x72, 0x1a, 0x13, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x4c, 0x6f, 0x67,
	0x73, 0x2e, 0x52, 0x73, 0x70, 0x5f, 0x41, 0x6c, 0x6c, 0x12, 0x41, 0x0a, 0x0c, 0x62, 0x6f, 0x73,
	0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x12, 0x1c, 0x2e, 0x62, 0x6f, 0x72, 0x72,
	0x6f, 0x77, 0x4c, 0x6f, 0x67, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x5f, 0x42, 0x6f, 0x73, 0x73, 0x5f,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x1a, 0x13, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77,
	0x4c, 0x6f, 0x67, 0x73, 0x2e, 0x52, 0x73, 0x70, 0x5f, 0x41, 0x6c, 0x6c, 0x42, 0x12, 0x5a, 0x10,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x4c, 0x6f, 0x67, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_borrowLogs_proto_rawDescOnce sync.Once
	file_proto_borrowLogs_proto_rawDescData = file_proto_borrowLogs_proto_rawDesc
)

func file_proto_borrowLogs_proto_rawDescGZIP() []byte {
	file_proto_borrowLogs_proto_rawDescOnce.Do(func() {
		file_proto_borrowLogs_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_borrowLogs_proto_rawDescData)
	})
	return file_proto_borrowLogs_proto_rawDescData
}

var file_proto_borrowLogs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_borrowLogs_proto_goTypes = []interface{}{
	(*ReqToOther)(nil),       // 0: borrowLogs.Req_to_other
	(*Req_Boss_Confirm)(nil), // 1: borrowLogs.Req_Boss_Confirm
	(*Rsp_All)(nil),          // 2: borrowLogs.Rsp_All
}
var file_proto_borrowLogs_proto_depIdxs = []int32{
	0, // 0: borrowLogs.borrowLogs.to_other:input_type -> borrowLogs.Req_to_other
	1, // 1: borrowLogs.borrowLogs.boss_confirm:input_type -> borrowLogs.Req_Boss_Confirm
	2, // 2: borrowLogs.borrowLogs.to_other:output_type -> borrowLogs.Rsp_All
	2, // 3: borrowLogs.borrowLogs.boss_confirm:output_type -> borrowLogs.Rsp_All
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_borrowLogs_proto_init() }
func file_proto_borrowLogs_proto_init() {
	if File_proto_borrowLogs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_borrowLogs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqToOther); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_borrowLogs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_Boss_Confirm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_borrowLogs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp_All); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_borrowLogs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_borrowLogs_proto_goTypes,
		DependencyIndexes: file_proto_borrowLogs_proto_depIdxs,
		MessageInfos:      file_proto_borrowLogs_proto_msgTypes,
	}.Build()
	File_proto_borrowLogs_proto = out.File
	file_proto_borrowLogs_proto_rawDesc = nil
	file_proto_borrowLogs_proto_goTypes = nil
	file_proto_borrowLogs_proto_depIdxs = nil
}
